# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 550
indent-width = 4

[lint]
select = ["E4", "E7", "E9", "F", "B"]
ignore = ["E265", "E402", "F403", "F405", "F821", "E731", "E225", "E231", "E301", "E305", "E251", "E201", "E202", "E203", "E221", "E226", "E241", "E741"]