# Add additional sync excludes for this repo
exclude README.md
exclude package
exclude cmk_addons/plugins/TEMPLATE
exclude tests/unit/cmk_addons/plugins/TEMPLATE
exlucde .devcontainer/template_sync.conf