#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# This is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation in version 2. check_mk is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along
# with GNU Make; see the file COPYING. If not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.

# WAGNER AG
# Developer: opensource@wagner.ch

"""
Check_MK agent based checks to be used with agent_fortios Datasource

"""

from collections.abc import Mapping, Sequence

from cmk.base.check_api import passwordstore_get_cmdline
from cmk.base.config import special_agent_info


def agent_arguments_fortios(params: Mapping[str, object], hostname: str, ipaddress: str | None) -> Sequence[str | tuple[str, str, str]]:
    args: list[str | tuple[str, str, str]] = ["--timeout", str(timeout)] if (timeout := params.get("timeout")) else []
    port = params.get("port")
    if port:
        args += ["--port", port]
    debug = params.get("debug")
    if debug:
        args += ["--debug", debug]

    cert_verify = params.get("ssl", True)
    if cert_verify is False:
        args.append("--no-cert-check")
    elif cert_verify is True:
        args += ["--cert-server-name", hostname]
    else:
        args += ["--cert-server-name", str(cert_verify)]

    api_token = params.get("api_token")
    if isinstance(api_token, (str, tuple)):
        args += ["--api-token", passwordstore_get_cmdline("%s", api_token)]

    return [*args, ipaddress or hostname]


special_agent_info["fortios"] = agent_arguments_fortios
