name: Lint

on:
  push:
    paths:
      - '**.py'

jobs:
  ruff_lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11

    - name: Install Ruff
      run: pip install ruff

    - name: Run Ruff
      uses: jpetrucciani/ruff-check@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}